<a href="https://colab.research.google.com/github/PrajwalSathyanarayana/TensorFlow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch #import PyTorch library
torch.Tensor #refers to Tensor class within the torch library.
# A Tensor is a fundamental data structure in PyTorch; it's a multi dimensional array,
# similar to NumPy arrays.

torch.Tensor

In [2]:
# Create a new tensor in PyTorch.
x = torch.tensor([1.0, 2.0], requires_grad=True)
print(x)

notes = '''
[1.0, 2.0] - data that tensor x will hold.
requires_grad = True - important argument that enables automatic differentiation.
It allows PyTorch to track all operations performed on a tensor, and automatically computes the
gradient of any function with respect to this tensor later on.
'''

tensor([1., 2.], requires_grad=True)


In [3]:
y = x * 2
z = y.sum()
print(y)
print(z)
notes = '''
- y = x*2 - performs element wise multiplication of tensor x by scalar value 2.
- [1.0, 2.0] * 2 = [2.0, 4.0]
- Python automatically tracks this multiplication operation;
indicating that this tensor y was created as a result of a multiplication operation and PyTorch
can compute gradients with respect to it.
- z = y.sum() - computes the sum of all elements in the tensor y.
- 2.0 + 4.0 = 6.0 i.e., single element tensor.
- This sum operation is also tracked.
'''

tensor([2., 4.], grad_fn=<MulBackward0>)
tensor(6., grad_fn=<SumBackward0>)


In [4]:
print(z.backward())

None


In [5]:
torch.__version__

'2.9.0+cu128'

In [6]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [7]:
tensor0d = torch.tensor(1) # scalar; 0D tensor
tensor1d = torch.tensor([1,2,3]) # vector; 1D tensor
tensor2d = torch.tensor([[1,2],
                         [3,4]]) # matrix; 2D tensor - rows and columns
tensor3d = torch.tensor([[[1,2], [3,4]],
                         [[5,6], [7,8]]]) # tensor; 3D tensor - collection of 2D matrics
print(tensor0d)
print(tensor1d)
print(tensor2d)
print(tensor3d)

tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [8]:
print(tensor0d.dtype)

torch.int64


In [9]:
#LOGISTIC REGRESSION FORWARD PASS
import torch.nn.functional as F #import the functional module containing various activation, loss functions and other operations
y = torch.tensor([1.0]) # true label i.e., actual output
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight parameter
b = torch.tensor([0.0]) # bias unit
z = x1 * w1 + b # net input i.e., 1.1 * 2.2 + 0.0 = 2.42
a = torch.sigmoid(z) # applies sigmoid activation function to net input 'z'; sigmoid squashes any real valued number into a
# range between 0 and 1, making it suitable for binary classification probabilites. 'a' represents the predicted output or
# activation of logistic regression model.
loss = F.binary_cross_entropy(a,y) # calculate the binary cross entropy loss between predicted output 'a' and true label 'y'
print(z)
print(a)
print(loss)

tensor([2.4200])
tensor([0.9183])
tensor(0.0852)
